
set prg "./testwinsizes"

#gem_start $prg

spawn "$prg"

match ".*POSITION/SIZE of blue.*\n.*CTRL-D RETURN.*" "$prg Initial prompt"
send "10 10 100 100\n"
match ".*POSITION/SIZE of blue.*\n.*CTRL-D RETURN.*" "$prg prompt 2"
send "100 100 50 50\n"
match ".*POSITION/SIZE of blue.*\n.*CTRL-D RETURN.*" "$prg prompt 3"
send "10 10 50 50\n"
match ".*POSITION/SIZE of blue.*\n.*CTRL-D RETURN.*" "$prg prompt 4"
send "^D\n"
match ".*RETURN to exit.*$" "$prg waits exit key"
send "\n"
match eof "$prg correct end"
