
_OA_DL_IMPORT extern void
Am_Widget_General_Undo_Redo(Am_Object command_obj, bool undo, bool selective);
_OA_DL_IMPORT extern Am_Object_Method Am_Widget_Inter_Command_Undo;
_OA_DL_IMPORT extern Am_Object_Method Am_Widget_Inter_Command_Selective_Undo;
_OA_DL_IMPORT extern Am_Object_Method Am_Widget_Inter_Command_Selective_Repeat;
