/* ************************************************************* *
 *   The Amulet User Interface Development Environment           *
 * ************************************************************* *
 *   Created automatically by the Gilt program in Amulet.        *
 *   Do not edit this file directly.                             *
 *   For more information on Amulet, contact amulet@cs.cmu.edu   *
 * ************************************************************* *
 *   Generated on Wed Jan 29 11:01:44 1997

 *   Amulet version 3.0 alpha
 * ************************************************************* */
#ifndef example2db_H
#define example2db_H

#include <amulet.h>

extern Am_Object example2db;
extern Am_Object example2db_Initialize ();

extern Am_Slot_Key GILT_DB_VALUE;

#endif
