_OA_DL_IMPORT extern Am_Formula Am_Active_From_Command;
_OA_DL_IMPORT extern Am_Formula Am_Active_And_Active2;
_OA_DL_IMPORT extern Am_Formula Am_Get_Owners_Command;
_OA_DL_IMPORT extern Am_Formula Am_Get_Real_String_Or_Obj;
_OA_DL_IMPORT extern Am_Formula Am_Get_Button_Command_Value;
_OA_DL_IMPORT extern Am_Formula Am_Font_From_Owner;
