/* ************************************************************* *
 *   The Amulet User Interface Development Environment           *
 * ************************************************************* *
 *   Created automatically by the Gilt program in Amulet.        *
 *   Do not edit this file directly.                             *
 *   For more information on Amulet, contact amulet@cs.cmu.edu   *
 * ************************************************************* *
 *   Generated on Wed Jan 22 00:33:39 1997

 *   Amulet version 3.0 alpha
 * ************************************************************* */

#include <amulet.h>

Am_Object About_Gilt_Window;

Am_Object
About_Gilt_Window_Initialize()
{
  About_Gilt_Window =
      Am_Window.Create("About_Gilt_Window")
          .Set(Am_DESTROY_WINDOW_METHOD,
               Am_Default_Pop_Up_Window_Destroy_Method)
          .Set(Am_FILL_STYLE, Am_Amulet_Purple)
          .Set(Am_TITLE, "Gilt: The Amulet Interface Builder")
          .Set(Am_ICON_TITLE, "About Gilt")
          .Set(Am_WIDTH, 472)
          .Set(Am_HEIGHT, 177)
          .Add_Part(Am_Border_Rectangle.Create()
                        .Set(Am_LEFT, 13)
                        .Set(Am_TOP, 12)
                        .Set(Am_WIDTH, 450)
                        .Set(Am_HEIGHT, 150)
                        .Set(Am_SELECTED, 0)
                        .Set(Am_FILL_STYLE, Am_Amulet_Purple))
          .Add_Part(Am_Text.Create()
                        .Set(Am_LEFT, Am_Center_X_Is_Center_Of_Owner)
                        .Set(Am_TOP, 22)
                        .Set(Am_WIDTH, 374)
                        .Set(Am_HEIGHT, 19)
                        .Set(Am_TEXT, "Gilt: The Amulet Interface Builder")
                        .Set(Am_FONT, Am_Font(Am_FONT_FIXED, true, false, false,
                                              Am_FONT_LARGE))
                        .Set(Am_LINE_STYLE, Am_Blue)
                        .Set(Am_FILL_STYLE, Am_No_Style))
          .Add_Part(Am_Text.Create()
                        .Set(Am_LEFT, 21)
                        .Set(Am_TOP, 90)
                        .Set(Am_WIDTH, 189)
                        .Set(Am_HEIGHT, 13)
                        .Set(Am_TEXT, "Created by the Amulet group")
                        .Set(Am_FONT, Am_Font(Am_FONT_FIXED, false, true, false,
                                              Am_FONT_MEDIUM))
                        .Set(Am_LINE_STYLE, Am_Black)
                        .Set(Am_FILL_STYLE, Am_No_Style))
          .Add_Part(Am_Text.Create()
                        .Set(Am_LEFT, 21)
                        .Set(Am_TOP, 107)
                        .Set(Am_WIDTH, 427)
                        .Set(Am_HEIGHT, 13)
                        .Set(Am_TEXT, "Based on AmEdit by S. Nebel from "
                                      "Linkworks Ltd, Wellington NZ")
                        .Set(Am_FONT, Am_Font(Am_FONT_FIXED, false, true, false,
                                              Am_FONT_MEDIUM))
                        .Set(Am_LINE_STYLE, Am_Black)
                        .Set(Am_FILL_STYLE, Am_No_Style))
          .Add_Part(Am_Text.Create()
                        .Set(Am_LEFT, Am_Center_X_Is_Center_Of_Owner)
                        .Set(Am_TOP, 42)
                        .Set(Am_WIDTH, 187)
                        .Set(Am_HEIGHT, 22)
                        .Set(Am_TEXT, "Version " Am_VERSION)
                        .Set(Am_FONT, Am_Font(Am_FONT_FIXED, false, false,
                                              false, Am_FONT_LARGE))
                        .Set(Am_LINE_STYLE, Am_Blue)
                        .Set(Am_FILL_STYLE, Am_No_Style))
          .Add_Part(Am_Text.Create()
                        .Set(Am_LEFT, 45)
                        .Set(Am_TOP, 62)
                        .Set(Am_WIDTH, 389)
                        .Set(Am_HEIGHT, 19)
                        .Set(Am_TEXT, "A \"Graphical Interface Layout Tool\"")
                        .Set(Am_FONT, Am_Font(Am_FONT_FIXED, true, false, false,
                                              Am_FONT_LARGE))
                        .Set(Am_LINE_STYLE, Am_Blue)
                        .Set(Am_FILL_STYLE, Am_No_Style))
          .Add_Part(Am_Line.Create()
                        .Set(Am_X1, 76)
                        .Set(Am_Y1, 80)
                        .Set(Am_X2, 87)
                        .Set(Am_Y2, 80)
                        .Set(Am_LINE_STYLE, Am_Blue))
          .Add_Part(Am_Line.Create()
                        .Set(Am_X1, 187)
                        .Set(Am_Y1, 80)
                        .Set(Am_X2, 198)
                        .Set(Am_Y2, 80)
                        .Set(Am_LINE_STYLE, Am_Blue))
          .Add_Part(Am_Line.Create()
                        .Set(Am_X1, 297)
                        .Set(Am_Y1, 80)
                        .Set(Am_X2, 308)
                        .Set(Am_Y2, 80)
                        .Set(Am_LINE_STYLE, Am_Blue))
          .Add_Part(Am_Line.Create()
                        .Set(Am_X1, 374)
                        .Set(Am_Y1, 80)
                        .Set(Am_X2, 385)
                        .Set(Am_Y2, 80)
                        .Set(Am_LINE_STYLE, Am_Blue))

          .Add_Part(Am_Button_Panel.Create()
                        .Set(Am_LEFT, Am_Center_X_Is_Center_Of_Owner)
                        .Set(Am_TOP, 124)
                        .Set(Am_FILL_STYLE, Am_Amulet_Purple)
                        .Set(Am_LAYOUT, Am_Vertical_Layout)
                        .Set(Am_H_SPACING, 0)
                        .Set(Am_V_SPACING, 0)
                        .Set(Am_MAX_RANK, 0)
                        .Set(Am_ITEMS, Am_Value_List().Add(
                                           Am_Standard_OK_Command.Create())));
  return About_Gilt_Window;
}
