/* ************************************************************* *
 *   The Amulet User Interface Development Environment           *
 * ************************************************************* *
 *   Created automatically by the Gilt program in Amulet.        *
 *   Do not edit this file directly.                             *
 *   For more information on Amulet, contact amulet@cs.cmu.edu   *
 * ************************************************************* *
 *   Generated on Thu Aug 07 12:56:21 1997

 *   Amulet version 4.0 Development
 * ************************************************************* */
#ifndef Conflict_Window_H
#define Conflict_Window_H

#include <amulet.h>

extern Am_Object Conflict_Window;
extern Am_Object Conflict_Window_Initialize ();

//Line styles exclusivly created by Gilt

extern Am_Style Am_White_2







#endif
