/* ************************************************************* *
 *   The Amulet User Interface Development Environment           *
 * ************************************************************* *
 *   Created automatically by the Gilt program in Amulet.        *
 *   Do not edit this file directly.                             *
 *   For more information on Amulet, contact amulet@cs.cmu.edu   *
 * ************************************************************* *
 *   Generated on Wed Jan 22 13:31:26 1997

 *   Amulet version 3.0 alpha
 * ************************************************************* */

#include <amulet.h>
#include "externs.h"

Am_Object Name_And_Label_Window;
Am_Object Name_And_Image_Window;

Am_Object Name_And_Label_Window_Initialize (bool is_bitmap) {
  ((is_bitmap) ? Name_And_Image_Window : Name_And_Label_Window) 
    = Am_Window.Create((is_bitmap) ? "Name_And_Image_Window" : "Name_And_Label_Window")
    .Set(Am_DESTROY_WINDOW_METHOD, Am_Default_Pop_Up_Window_Destroy_Method)
    .Set(Am_FILL_STYLE, Am_Motif_Light_Gray)
    .Set(Am_TITLE, (is_bitmap) ? "Name and Image Setting" : "Name and Label Setting")
    .Set(Am_ICON_TITLE, (is_bitmap) ? "Settings: Name and Image File for Bitmap Object"
	 : "Settings: Name and Label")
    .Set(Am_WIDTH, 389)
    .Set(Am_HEIGHT, 132)
    .Add_Part(Am_Border_Rectangle.Create()
      .Set(Am_LEFT, 0)
      .Set(Am_TOP, 0)
      .Set(Am_WIDTH, 389)
      .Set(Am_HEIGHT, 132)
      .Set(Am_SELECTED, 0)
      .Set(Am_FILL_STYLE, Am_Motif_Light_Gray)
    )
    .Add_Part(NAME_OBJ, Am_Text_Input_Widget.Create("NAME_OBJ")
      .Set(Am_LEFT, 14)
      .Set(Am_TOP, 13)
      .Set(Am_WIDTH, 319)
      .Set(Am_HEIGHT, 24)
      .Get_Object(Am_COMMAND)
        .Set(Am_LABEL, "Name for item:")
        .Get_Owner()
      .Set(Am_FILL_STYLE, Am_Motif_Light_Gray), Am_OK_IF_THERE
    )
    .Add_Part(Am_Button_Panel.Create()
      .Set(Am_LEFT, 113)
      .Set(Am_TOP, 84)
      .Set(Am_FILL_STYLE, Am_Motif_Light_Gray)
      .Set(Am_LAYOUT, Am_Horizontal_Layout)
      .Set(Am_H_SPACING, 40)
      .Set(Am_V_SPACING, 0)
      .Set(Am_MAX_RANK, 0)
      .Set(Am_ITEMS, Am_Value_List()
        .Add(Am_Standard_OK_Command.Create())
        .Add(Am_Standard_Cancel_Command.Create())
        )
    )
    .Add_Part(LABEL_OBJ, Am_Text_Input_Widget.Create("LABEL")
      .Set(Am_LEFT, (is_bitmap) ? 14 : 70)
      .Set(Am_TOP, 40)
      .Set(Am_WIDTH, 263)
      .Set(Am_HEIGHT, 25)
      .Get_Object(Am_COMMAND)
        .Set(Am_LABEL, (is_bitmap) ? "Image File:" : "Label")
        .Get_Owner()
      .Set(Am_FILL_STYLE, Am_Motif_Light_Gray), Am_OK_IF_THERE
    )
    .Add_Part(Am_Tab_To_Next_Widget_Interactor.Create())
  ;
  return Name_And_Label_Window;
}
