/* ************************************************************* *
 *   The Amulet User Interface Development Environment           *
 * ************************************************************* *
 *   Created automatically by the Gilt program in Amulet.        *
 *   Do not edit this file directly.                             *
 *   For more information on Amulet, contact amulet@cs.cmu.edu   *
 * ************************************************************* *
 *   Generated on Sun Aug 03 02:04:11 1997

 *   Amulet version 4.0 Development
 * ************************************************************* */
#ifndef Offset_Percentage_Dialog_H
#define Offset_Percentage_Dialog_H

#include <amulet.h>

extern Am_Object Offset_Percentage_Dialog;
extern Am_Object Offset_Percentage_Dialog_Initialize();

// Line styles exclusivtely created by Gilt

#endif
