/* ************************************************************* *
 *   The Amulet User Interface Development Environment           *
 * ************************************************************* *
 *   Created automatically by the Gilt program in Amulet.        *
 *   Do not edit this file directly.                             *
 *   For more information on Amulet, contact amulet@cs.cmu.edu   *
 * ************************************************************* *
 *   Generated on Tue Jan 21 22:40:29 1997

 *   Amulet version 3.0 alpha
 * ************************************************************* */
#ifndef MainWindow_H
#define MainWindow_H

#include <amulet.h>

extern Am_Object savecpp_window;
extern Am_Object savecpp_window_Initialize();

extern Am_Slot_Key EXPLICIT_SIZE_OBJ;
extern Am_Slot_Key H_FILENAME;
extern Am_Slot_Key CREATE_HEADER;
extern Am_Slot_Key MAIN_NAME;
extern Am_Slot_Key WINDOW_OR_GROUP;
extern Am_Slot_Key WIN_TITLE;
extern Am_Slot_Key WIDTH_OBJ;
extern Am_Slot_Key HEIGHT_OBJ;
extern Am_Slot_Key FIXED_SIZE_OBJ;
extern Am_Slot_Key C_FILENAME;

extern ofstream cc_out_file;
extern bool want_h_file;
extern ofstream h_out_file;

#endif
