/* ************************************************************* *
 *   The Amulet User Interface Development Environment           *
 * ************************************************************* *
 *   Created automatically by the Gilt program in Amulet.        *
 *   Do not edit this file directly.                             *
 *   For more information on Amulet, contact amulet@cs.cmu.edu   *
 * ************************************************************* *
 *   Generated on Wed Jan 22 13:45:56 1997

 *   Amulet version 3.0 alpha
 * ************************************************************* */

#include <amulet.h>
#include "externs.h"

Am_Object Scroll_Group_Window;

Am_Slot_Key SCROLL_PROPS_OBJ = Am_Register_Slot_Name("SCROLL_PROPS_OBJ");

Am_Object
Scroll_Group_Window_Initialize()
{
  Scroll_Group_Window =
      Am_Window.Create("scroll_group_window")
          .Set(Am_FILL_STYLE, Am_Motif_Light_Gray)
          .Set(Am_TITLE, "Scroll Group Settings")
          .Set(Am_ICON_TITLE, "Settings: Scroll Group")
          .Set(Am_WIDTH, 389)
          .Set(Am_HEIGHT, 272)
          .Add_Part(Am_Border_Rectangle.Create()
                        .Set(Am_LEFT, 0)
                        .Set(Am_TOP, 0)
                        .Set(Am_WIDTH, 389)
                        .Set(Am_HEIGHT, 272)
                        .Set(Am_SELECTED, 0)
                        .Set(Am_FILL_STYLE, Am_Motif_Light_Gray))
          .Add_Part(NAME_OBJ, Am_Text_Input_Widget.Create("NAME_OBJ")
                                  .Set(Am_LEFT, 14)
                                  .Set(Am_TOP, 13)
                                  .Set(Am_WIDTH, 319)
                                  .Set(Am_HEIGHT, 24)
                                  .Get_Object(Am_COMMAND)
                                  .Set(Am_LABEL, "Name for item:")
                                  .Get_Owner()
                                  .Set(Am_FILL_STYLE, Am_Motif_Light_Gray))
          .Add_Part(
              Am_Button_Panel.Create()
                  .Set(Am_LEFT, 114)
                  .Set(Am_TOP, 222)
                  .Set(Am_FILL_STYLE, Am_Motif_Light_Gray)
                  .Set(Am_LAYOUT, Am_Horizontal_Layout)
                  .Set(Am_H_SPACING, 40)
                  .Set(Am_V_SPACING, 0)
                  .Set(Am_MAX_RANK, 0)
                  .Set(Am_ITEMS, Am_Value_List()
                                     .Add(Am_Standard_OK_Command.Create())
                                     .Add(Am_Standard_Cancel_Command.Create())))
          .Add_Part(Am_INNER_WIDTH, Am_Number_Input_Widget.Create("inner_width")
                                        .Set(Am_LEFT, 27)
                                        .Set(Am_TOP, 47)
                                        .Set(Am_WIDTH, 306)
                                        .Set(Am_HEIGHT, 25)
                                        .Set(Am_FILL_STYLE, Am_Motif_Light_Gray)
                                        .Get_Object(Am_COMMAND)
                                        .Set(Am_LABEL, " Inner Width")
                                        .Get_Owner()
                                        .Set(Am_VALUE_1, Am_No_Value)
                                        .Set(Am_VALUE_2, Am_No_Value))
          .Add_Part(Am_INNER_HEIGHT,
                    Am_Number_Input_Widget.Create("inner_height")
                        .Set(Am_LEFT, 27)
                        .Set(Am_TOP, 83)
                        .Set(Am_WIDTH, 306)
                        .Set(Am_HEIGHT, 25)
                        .Set(Am_FILL_STYLE, Am_Motif_Light_Gray)
                        .Get_Object(Am_COMMAND)
                        .Set(Am_LABEL, "Inner Height")
                        .Get_Owner()
                        .Set(Am_VALUE_1, Am_No_Value)
                        .Set(Am_VALUE_2, Am_No_Value))
          .Add_Part(SCROLL_PROPS_OBJ,
                    Am_Checkbox_Panel.Create()
                        .Set(Am_LEFT, 42)
                        .Set(Am_TOP, 119)
                        .Set(Am_FILL_STYLE, Am_Motif_Light_Gray)
                        .Set(Am_ITEMS,
                             Am_Value_List()
                                 .Add(Am_Command.Create()
                                          .Set(Am_LABEL, "Vertical Scrollbar")
                                          .Set(Am_ID, 1))
                                 .Add(Am_Command.Create()
                                          .Set(Am_LABEL, "Horizontal Scrollbar")
                                          .Set(Am_ID, 2))
                                 .Add(Am_Command.Create()
                                          .Set(Am_LABEL, "Scrollbar on top")
                                          .Set(Am_ID, 3))
                                 .Add(Am_Command.Create()
                                          .Set(Am_LABEL, "Scrollbar on left")
                                          .Set(Am_ID, 4)))
                        .Set(Am_LAYOUT, Am_Vertical_Layout)
                        .Set(Am_H_SPACING, 0)
                        .Set(Am_V_SPACING, -3)
                        .Set(Am_MAX_RANK, 0))
          .Add_Part(Am_Tab_To_Next_Widget_Interactor.Create());
  return Scroll_Group_Window;
}
