/* ************************************************************* *
 *   The Amulet User Interface Development Environment           *
 * ************************************************************* *
 *   Created automatically by the Gilt program in Amulet.        *
 *   Do not edit this file directly.                             *
 *   For more information on Amulet, contact amulet@cs.cmu.edu   *
 * ************************************************************* *
 *   Generated on Thu Jul 17 16:01:16 1997

 *   Amulet version 3.0
 * ************************************************************* */

#include <amulet.h>
#include OBJECT__H			// am_object
#include OPAL__H			// am_window
#include STANDARD_SLOTS__H	// am_destroy_window_method
#include WIDGETS__H			// am_default_pop_up_window_destroy_method

Am_Object askpositionandsize;

Am_Object askpositionandsize_Initialize () {
  askpositionandsize = Am_Window.Create(DSTR("askpositionandsize"))
    .Set(Am_DESTROY_WINDOW_METHOD, Am_Default_Pop_Up_Window_Destroy_Method)
    .Set(Am_FILL_STYLE, Am_Amulet_Purple)
    .Set(Am_TITLE, "Choose Position and Size")
    .Set(Am_ICON_TITLE, "Choose Position and Size")
    .Set(Am_WIDTH , Am_Width_Of_Parts)
    .Set(Am_HEIGHT, Am_Height_Of_Parts)
    ;
  askpositionandsize
    .Add_Part(Am_Text.Create()
      .Set(Am_LEFT, 16)
      .Set(Am_TOP, 16)
      .Set(Am_WIDTH, 455)
      .Set(Am_HEIGHT, 15)
      .Set(Am_TEXT, "Please press and drag in the window to specify position and size ")
      .Set(Am_LINE_STYLE, Am_Black)
      .Set(Am_FILL_STYLE, Am_No_Style)
    )
    .Add_Part(Am_Text.Create()
      .Set(Am_LEFT, 16)
      .Set(Am_TOP, 99)
      .Set(Am_WIDTH, 301)
      .Set(Am_HEIGHT, 15)
      .Set(Am_TEXT, "or hit Cancel to stop executing the script.")
      .Set(Am_LINE_STYLE, Am_Black)
      .Set(Am_FILL_STYLE, Am_No_Style)
    )
    .Add_Part(Am_Button_Panel.Create()
      .Set(Am_LEFT, 152)
      .Set(Am_TOP, 126)
      .Set(Am_FILL_STYLE, Am_Amulet_Purple)
      .Set(Am_LAYOUT, Am_Horizontal_Layout)
      .Set(Am_H_SPACING, 10)
      .Set(Am_V_SPACING, 0)
      .Set(Am_MAX_RANK, 0)
      .Set(Am_ITEMS, Am_Value_List()
        .Add(Am_Standard_OK_Command.Create())
        .Add(Am_Standard_Cancel_Command.Create())
        )
    )
    .Add_Part(Am_Text.Create()
      .Set(Am_LEFT, 16)
      .Set(Am_TOP, 58)
      .Set(Am_WIDTH, 161)
      .Set(Am_HEIGHT, 15)
      .Set(Am_TEXT, "or fill in values here:")
      .Set(Am_LINE_STYLE, Am_Black)
      .Set(Am_FILL_STYLE, Am_No_Style)
    )
    .Add_Part(Am_Text_Input_Widget.Create()
      .Set(Am_LEFT, 190)
      .Set(Am_TOP, 37)
      .Set(Am_WIDTH, 115)
      .Set(Am_HEIGHT, 25)
      .Get_Object(Am_COMMAND)
        .Set(Am_LABEL, "Left")
        .Get_Owner()
      .Set(Am_FILL_STYLE, Am_Amulet_Purple)
    )
    .Add_Part(Am_Text_Input_Widget.Create()
      .Set(Am_LEFT, 197)
      .Set(Am_TOP, 63)
      .Set(Am_WIDTH, 108)
      .Set(Am_HEIGHT, 25)
      .Get_Object(Am_COMMAND)
        .Set(Am_LABEL, "Top")
        .Get_Owner()
      .Set(Am_FILL_STYLE, Am_Amulet_Purple)
    )
    .Add_Part(Am_Text_Input_Widget.Create()
      .Set(Am_LEFT, 322)
      .Set(Am_TOP, 37)
      .Set(Am_WIDTH, 115)
      .Set(Am_HEIGHT, 25)
      .Get_Object(Am_COMMAND)
        .Set(Am_LABEL, "Width")
        .Get_Owner()
      .Set(Am_FILL_STYLE, Am_Amulet_Purple)
    )
    .Add_Part(Am_Text_Input_Widget.Create()
      .Set(Am_LEFT, 315)
      .Set(Am_TOP, 63)
      .Set(Am_WIDTH, 122)
      .Set(Am_HEIGHT, 25)
      .Get_Object(Am_COMMAND)
        .Set(Am_LABEL, "Height")
        .Get_Owner()
      .Set(Am_FILL_STYLE, Am_Amulet_Purple)
    )
    .Add_Part(Am_Tab_To_Next_Widget_Interactor.Create())
  ;
  return askpositionandsize;
}
